name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - source  # 看你截图里显示分支名是 source，请务必匹配

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 自动拉取子模块
          fetch-depth: 0

      # 如果你没用子模块，就在这里强制下载主题
      - name: Force Download Theme
        run: |
          mkdir -p themes
          git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
